// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "GridFieldExtensions.ADD_CLASS": "Add: <i>{classname}</i>",
    "GridFieldExtensions.CONFIRMDEL": "Are you sure you want to delete this?",
    "GridFieldExtensions.OPEN_SEARCH_FILTER": "Open search and filter",
    "GridFieldExtensions.SAVE_PUBLISH": "Save & publish"
});
}