// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "GridFieldExtensions.ADD_CLASS": "Aldoni: <i>{classname}</i>",
    "GridFieldExtensions.CONFIRMDEL": "Ĉu vi certas ke vi volas forigi tion?",
    "GridFieldExtensions.OPEN_SEARCH_FILTER": "Malfermi serĉon kaj filtrilon",
    "GridFieldExtensions.SAVE_PUBLISH": "Konservi kaj publikigi"
});
}