// This file was generated by silverstripe/tx-translator from client/lang/src/it.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "GridFieldExtensions.ADD_CLASS": "Aggiungi: <i>{classname}</i>",
    "GridFieldExtensions.CONFIRMDEL": "Sei sicuro di volerlo eliminare?",
    "GridFieldExtensions.OPEN_SEARCH_FILTER": "Apri ricerca e filtraggio",
    "GridFieldExtensions.SAVE_PUBLISH": "Salva & pubblica"
});
}