// This file was generated by silverstripe/tx-translator from client/lang/src/nl_NL.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl_NL', {
    "GridFieldExtensions.ADD_CLASS": "Toevoegen: <i>{classname}</i>",
    "GridFieldExtensions.CONFIRMDEL": "Weet je zeker dat je dit wil verwijderen?",
    "GridFieldExtensions.OPEN_SEARCH_FILTER": "Open zoeken en filteren",
    "GridFieldExtensions.SAVE_PUBLISH": "Opslaan & Publiceren"
});
}