// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "GridFieldExtensions.ADD_CLASS": "Pridať: <i>{classname}</i>",
    "GridFieldExtensions.CONFIRMDEL": "Naozaj to chcete odstrániť?",
    "GridFieldExtensions.OPEN_SEARCH_FILTER": "Otvorte vyhľadávanie a filter",
    "GridFieldExtensions.SAVE_PUBLISH": "Uložiť a zverejniť"
});
}