name: Dispatch CI

on:
  # At 9:45 PM UTC, only on Wednesday and Thursday
  schedule:
    - cron: '45 21 * * 3,4'

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the symbiote account
    if: (github.event_name == 'schedule' && github.repository_owner == 'symbiote') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch CI
        uses: silverstripe/gha-dispatch-ci@v1
