name: Keepalive

on:
  # At 9:45 PM UTC, on day 18 of the month
  schedule:
    - cron: '45 21 18 * *'
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the symbiote account
    if: (github.event_name == 'schedule' && github.repository_owner == 'symbiote') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
